import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds the Word-faithful Caishengbao prototype", async () => {
  const html = await readFile(new URL("../.next/server/app/index.html", import.meta.url), "utf8");
  assert.match(html, /<title>财升宝智能化升级｜Word原型复刻 Demo<\/title>/i);
  assert.match(html, /发现/);
  assert.match(html, /看盘/);
  assert.match(html, /选股/);
  assert.match(html, /经典版联动/);
  assert.match(html, /浅蓝色AI页面/);
  assert.match(html, /aria-label="财升宝APP智能化升级交互原型"/);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape/);
});

test("keeps the prototype interactive, scoped, and accessible", async () => {
  const [page, layout, css, packageJson] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);
  assert.match(page, /^"use client";/);
  assert.match(page, /type Tab = "discover" \| "watch" \| "select"/);
  assert.match(page, /type SelectTab = "hot" \| "shape" \| "strategy"/);
  assert.match(page, /type ClassicView = "home" \| "quotes" \| "market" \| "trade" \| "wealth" \| "profile"/);
  assert.match(page, /type ReasoningMode = "smart" \| "fast" \| "deep" \| "classic"/);
  assert.match(page, /aria-label="向小原AI助手提问"/);
  assert.match(page, /role="status"/);
  assert.match(page, /from "lucide-react"/);
  assert.match(page, /<ChartNoAxesCombined size=\{21\}/);
  assert.match(page, /<ArrowLeftRight size=\{21\}/);
  assert.match(page, /<WalletCards size=\{21\}/);
  assert.match(page, /<UserRound size=\{21\}/);
  assert.match(page, /function ClassicHome/);
  assert.match(page, /aria-label="切换到AI版本"/);
  assert.match(page, /function BottomNav/);
  assert.match(page, /className="reasoning-menu"/);
  assert.match(page, /className="voice-listening"/);
  assert.match(page, /<Volume2 size=\{22\}/);
  assert.match(page, /className="quick-drawer"/);
  assert.match(page, /展开快捷入口/);
  assert.match(packageJson, /lucide-react/);
  assert.match(page, /function ContextAssistant/);
  assert.match(page, /function ClassicChatPage/);
  assert.match(page, /function HeaderAssistantButton/);
  assert.match(page, /function DiscoverBanner/);
  assert.match(page, /api\/recommendations\?placement=discover-banner/);
  assert.match(page, /function DailyReportPage/);
  assert.match(page, /自选分析日报/);
  assert.match(page, /持仓分析日报/);
  assert.match(page, /function GlobalSearchPage/);
  assert.match(page, /贵州茅台最近有什么重要公告/);
  assert.match(page, /type SearchAiPhase = "idle" \| "thinking" \| "streaming" \| "done"/);
  assert.match(page, /setTimeout\(\(\) => setAiPhase\("streaming"\), 2000\)/);
  assert.match(page, /search-stock-section/);
  assert.match(page, /search-news-section/);
  assert.match(page, /searchableFeatures/);
  assert.match(page, /来自经典版全局搜索/);
  assert.match(page, /量价齐升的板块能否承接主线地位/);
  assert.match(page, /function matchStockNavigationTargets/);
  assert.match(page, /stockCatalog\["300033"\].*stockCatalog\["600519"\]/);
  assert.match(page, /aria-label=\{`打开\$\{stock\.name\}股票详情`\}/);
  assert.match(page, /function-jump-actions/);
  assert.match(page, /已完成功能识别/);
  assert.match(page, /scrollRef\.current\.scrollTop = scrollRef\.current\.scrollHeight/);
  assert.doesNotMatch(page, /▣ AI解读/);
  assert.match(page, /function SourceDrawer/);
  assert.match(page, /查看数据来源/);
  assert.match(page, /financial-source-link/);
  assert.match(page, /function StockDetailPage/);
  assert.match(page, /已添加自选 · 去查看/);
  assert.match(page, /function toggleStock/);
  assert.match(page, /caishengbao-watchlist/);
  assert.match(page, /移除.*自选/);
  assert.match(page, /function StockHighlights/);
  assert.match(page, /市场印象/);
  assert.match(page, /看点筛选/);
  assert.match(page, /全部\(\{signals\.length\}\)/);
  assert.match(page, /小原AI助手基于公开信息整理/);
  assert.match(page, /ipAssets\.avatar/);
  assert.match(page, /function ArticleDetailPage/);
  assert.match(page, /文章较长，帮你快速看完要点/);
  assert.match(page, /article-summary-result/);
  assert.match(page, /article-deep-read/);
  assert.match(page, /article-insight-drawer/);
  assert.match(page, /role="dialog"/);
  assert.match(page, /article\.analysis/);
  assert.doesNotMatch(page, /ArticleDetailPage\(\{ article, onBack, onContinue/);
  assert.doesNotMatch(page, /className="article-followups"|className="article-continue"/);
  assert.doesNotMatch(page, /已收藏本次解读/);
  assert.doesNotMatch(page, /感谢你的反馈|已记录反馈/);
  assert.match(page, /function NativeFunctionPage/);
  assert.match(page, /银证转账/);
  assert.match(page, /国债逆回购/);
  assert.match(page, /AI定制选股/);
  assert.match(page, /查看选股结果/);
  assert.match(page, /function StockFinancialOverview/);
  assert.match(page, /function FinancialReportListPage/);
  assert.match(page, /reportTitle=\{selectedReport\}/);
  assert.doesNotMatch(page, /financial-observation|AI观察|继续提问/);
  assert.match(page, /financial-qa-current/);
  assert.match(page, /正在结合当前财报分析/);
  assert.doesNotMatch(page, /FinancialAssistantPage\(\{ onBack, onContinue/);
  assert.doesNotMatch(page, /盘中异动监测完毕/);
  assert.doesNotMatch(page, /className="ai-selection-entry"/);
  assert.match(page, /strategy-card-head/);
  assert.match(page, /event-timeline/);
  assert.match(page, /市场点评/);
  assert.match(page, /daily-market-brief/);
  assert.match(page, /flash-selection-feed/);
  assert.doesNotMatch(page, /研报/);
  assert.doesNotMatch(page, /盘面脉络，一眼看懂|watch-ip-banner|ip-scene-banner/);
  assert.doesNotMatch(page, /小原小贴士|ip-tip-strip/);
  assert.match(page, /aria-pressed=\{active\}/);
  assert.match(page, /className=\{active \? "selected" : ""\}/);
  assert.match(page, /className="daily-report-entry"/);
  assert.match(css, /discover-banner/);
  assert.match(css, /stock-detail-page/);
  assert.match(page, /Hi,我是小原AI助手，随时与您在线交流~/);
  assert.match(page, /\/ip\/xiaoyuan-avatar\.webp/);
  assert.match(page, /\/ip\/xiaoyuan-daily\.webp/);
  assert.match(page, /\/ip\/xiaoyuan-report\.webp/);
  assert.match(page, /以上内容由AI生成/);
  assert.doesNotMatch(page, /问财|AI小宝|向小宝提问/);
  assert.match(layout, /lang="zh-CN"/);
  assert.match(css, /@media\(max-width:480px\)/);
  assert.match(css, /focus-visible/);
  assert.match(css, /--brand:#d9232e/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  assert.doesNotMatch(page + layout, /codex-preview|_sites-preview/);
});
