import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds the Word-faithful Caishengbao prototype", async () => {
  const html = await readFile(new URL("../.next/server/app/index.html", import.meta.url), "utf8");
  assert.match(html, /<title>财升宝智能化升级｜Word原型复刻 Demo<\/title>/i);
  assert.match(html, /发现/);
  assert.match(html, /看盘/);
  assert.match(html, /选股/);
  assert.match(html, /经典版联动/);
  assert.match(html, /浅蓝色AI页面/);
  assert.match(html, /aria-label="财升宝APP智能化升级交互原型"/);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape/);
});

test("keeps the prototype interactive, scoped, and accessible", async () => {
  const [page, layout, css, packageJson] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../package.json", import.meta.url), "utf8"),
  ]);
  assert.match(page, /^"use client";/);
  assert.match(page, /type Tab = "discover" \| "watch" \| "select"/);
  assert.match(page, /type SelectTab = "hot" \| "shape" \| "strategy"/);
  assert.match(page, /aria-label="向小宝提问"/);
  assert.match(page, /role="status"/);
  assert.match(page, /nav-icon nav-chart/);
  assert.match(page, /nav-icon nav-trade/);
  assert.match(page, /nav-icon nav-wealth/);
  assert.match(page, /nav-icon nav-profile/);
  assert.match(page, /type ClassicView = "home" \| "quotes" \| "market" \| "trade" \| "wealth" \| "profile"/);
  assert.match(page, /function ClassicHome/);
  assert.match(page, /aria-label="切换到AI版本"/);
  assert.match(page, /className="robot-entry"/);
  assert.match(page, /股票\/基金\/资讯\/功能\/问答/);
  assert.match(page, /type ReasoningMode = "smart" \| "fast" \| "deep" \| "classic"/);
  assert.match(page, /className="reasoning-menu"/);
  assert.match(page, /className="voice-listening"/);
  assert.match(page, /className="speaker-icon"/);
  assert.match(page, /className="quick-drawer"/);
  assert.match(page, /展开快捷入口/);
  assert.match(page, /我的收藏/);
  assert.match(css, /nav-trade\.png/);
  assert.match(page, /function ContextAssistant/);
  assert.match(page, /最近的热点板块是什么/);
  assert.match(page, /打开国债逆回购/);
  assert.match(page, /一折基金都有哪些/);
  assert.match(page, /function ClassicChatPage/);
  assert.match(page, /展开到AI首页/);
  assert.match(page, /function HeaderAssistantButton/);
  assert.match(page, /className=\{`header-assistant/);
  assert.doesNotMatch(page, /className=\{`context-entry/);
  assert.match(css, /context-assistant-layer/);
  assert.match(css, /AI红白主题试用版/);
  assert.match(css, /linear-gradient\(105deg,#e92539,#ff533f\)/);
  assert.match(css, /我的页版头压缩与底部导航图标统一对齐/);
  assert.match(css, /\.profile-hero\{height:286px/);
  assert.match(page, /aria-label="打开小宝发现页"/);
  assert.match(page, /onSwitchAi=\{onBack\}/);
  assert.match(css, /经典版小宝独立发现页同步红白主题/);
  assert.match(page, /function WatchInsightModal/);
  assert.match(page, /补充搜索与总结已完成/);
  assert.match(page, /补充搜索来源/);
  assert.match(css, /watch-insight-layer/);
  assert.match(page, /function DiscoverBanner/);
  assert.match(page, /api\/recommendations\?placement=discover-banner/);
  assert.match(page, /function DailyReportPage/);
  assert.match(page, /自选分析日报/);
  assert.match(page, /持仓分析日报/);
  assert.match(page, /function GlobalSearchPage/);
  assert.match(page, /贵州茅台最近有什么重要公告/);
  assert.match(page, /type SearchAiPhase = "idle" \| "thinking" \| "streaming" \| "done"/);
  assert.match(page, /setTimeout\(\(\) => setAiPhase\("streaming"\), 2000\)/);
  assert.match(page, /search-stock-section/);
  assert.match(page, /search-news-section/);
  assert.match(page, /searchableFeatures/);
  assert.match(page, /function StockDetailPage/);
  assert.match(page, /已添加自选 · 去查看/);
  assert.match(page, /function toggleStock/);
  assert.match(page, /caishengbao-watchlist/);
  assert.match(page, /移除.*自选/);
  assert.match(page, /function StockHighlights/);
  assert.match(page, /市场印象/);
  assert.match(page, /function ArticleDetailPage/);
  assert.match(page, /正在阅读并总结原文/);
  assert.match(page, /streamedInsight/);
  assert.match(page, /继续追问/);
  assert.doesNotMatch(page, /article-insight-sheet/);
  assert.doesNotMatch(page, /已收藏本次解读/);
  assert.doesNotMatch(page, /感谢你的反馈|已记录反馈/);
  assert.match(page, /function NativeFunctionPage/);
  assert.match(page, /银证转账/);
  assert.match(page, /国债逆回购/);
  assert.match(page, /AI定制选股/);
  assert.match(page, /查看选股结果/);
  assert.match(page, /className="daily-report-entry"/);
  assert.match(css, /discover-banner/);
  assert.match(css, /stock-detail-page/);
  assert.match(page, /Hi,我是AI小宝，随时与您在线交流~/);
  assert.match(page, /function ClassicMarket/);
  assert.match(page, /function ClassicTrade/);
  assert.match(page, /function ClassicWealth/);
  assert.match(page, /function ClassicProfile/);
  assert.match(page, /onClick=\{\(\)=>onView\("quotes"\)\}/);
  assert.match(page, /\/xiaobao-avatar\.png/);
  assert.match(page, /以上内容由AI生成/);
  assert.doesNotMatch(page, /<b>▧<\/b>|<b>⇄<\/b>|<b>♙<\/b>/);
  assert.match(layout, /lang="zh-CN"/);
  assert.match(css, /@media\(max-width:480px\)/);
  assert.match(css, /prefers-color-scheme|@media|max-width/);
  assert.match(css, /语音播报图标精修/);
  assert.match(css, /voice-toggle:focus-visible/);
  assert.doesNotMatch(packageJson, /react-loading-skeleton/);
  assert.doesNotMatch(page + layout, /codex-preview|_sites-preview/);
});
